# Generated by Django 4.2.3 on 2023-07-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_of_week', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
